[package]
name = "gib-feature-types"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
gib-githost-types = { version = "0.1.0", path = "../gib-githost-types" }
non-empty-string = "0.2.4"
thiserror = "1.0.63"
