[workspace]
resolver = "2"

memebers = []
members = [
  "cli", 
  "core/bot", 
  "core/feature-types", 
  "core/githost-types", 
  "githost-github", 
  "features/improve-feature", 
  "features/label-feature", 
  "llm/llm-types", 
  "llm/llm-openai"
]
