[package]
name = "feature-types"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
githost-types = { version = "0.1.0", path = "../githost-types" }
non-empty-string = "0.2.4"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }
